# Generated by Django 5.2.4 on 2025-07-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts_and_taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Налог', 'verbose_name_plural': 'Налоги'},
        ),
    ]
